In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
arr = np.array([1,3,4,5,5,45,78,8,83,8,9,9,0,5,6,45,5,45])

In [5]:
arr=arr.reshape(9,2)

In [6]:
arr

array([[ 1,  3],
       [ 4,  5],
       [ 5, 45],
       [78,  8],
       [83,  8],
       [ 9,  9],
       [ 0,  5],
       [ 6, 45],
       [ 5, 45]])

In [11]:
np.argsort(arr, axis=0)

array([[6, 0],
       [0, 1],
       [1, 6],
       [2, 3],
       [8, 4],
       [7, 5],
       [5, 2],
       [3, 7],
       [4, 8]], dtype=int64)

In [12]:
np.argmax(arr)

8

In [9]:
np.argmin(arr)

12