## Basic numpy array attributes 

In [1]:
import numpy as np
a = np.array([[1,2,3.33,4, 8], [1,4,5,6,7]], dtype='float64')
print(type(a))

<class 'numpy.ndarray'>


In [2]:
a.shape

(2, 5)

In [3]:
a.ndim

2

In [4]:
a.size

10

In [5]:
a.dtype

dtype('float64')

In [6]:
a.itemsize

8

## Numpy function creation

In [7]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
np.empty((4,6))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511561e-306, 4.45025637e-307, 7.56593017e-307],
       [1.33508845e-306, 1.33511969e-306, 6.23037996e-307,
        4.45065276e-308, 8.90102881e-307, 1.24610383e-306],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306, 1.78018403e-306],
       [1.11261570e-306, 6.89804132e-307, 1.95820760e-306,
        6.23054972e-307, 1.24611266e-306, 2.22522596e-306]])

In [10]:
a

array([[1.  , 2.  , 3.33, 4.  , 8.  ],
       [1.  , 4.  , 5.  , 6.  , 7.  ]])

In [11]:
a*a

array([[ 1.    ,  4.    , 11.0889, 16.    , 64.    ],
       [ 1.    , 16.    , 25.    , 36.    , 49.    ]])

In [12]:
a / a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
a**a

array([[1.00000000e+00, 4.00000000e+00, 5.49211089e+01, 2.56000000e+02,
        1.67772160e+07],
       [1.00000000e+00, 2.56000000e+02, 3.12500000e+03, 4.66560000e+04,
        8.23543000e+05]])

## Slicing

In [14]:
arr1 = np.array([1,2,44,55,56,88])

In [15]:
a1 = arr1[2:5].copy()

In [16]:
a1

array([44, 55, 56])

In [19]:
a1[0] = 54
a1

array([54, 55, 56])

In [18]:
arr1

array([ 1,  2, 44, 55, 56, 88])

In [20]:
a[1,4]

7.0