In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine

In [2]:
wines = load_wine()

In [3]:
dir(wines)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [4]:
wines.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [5]:
wines.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [6]:
wines.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [7]:
wines.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [8]:
df = pd.DataFrame(wines.data, columns=wines.feature_names)

In [9]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [10]:
len(wines.data)

178

In [36]:
df['Categories'] = wines.target
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  Categories  
0                            3.92   1065.0           0  
1                            3.40   1050.0           0  
2                            3.17   1185.0           0  
3                            3.45   1480.0           0  
4                            2.93    735.0           0  
..                            ...      ...         ...  
173                          1.74    740.0           2  
174                          1.56    750.0           2  
175                          1.56    835.0           2  
176                          1.62    840.0           2  
177                          1.60    560.0           2  

[178 rows x 14 columns]

In [33]:
inputs = df.drop('Categories', axis="columns")

In [34]:
target = df.Categories

In [35]:
target

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: Categories, Length: 178, dtype: int32

In [42]:
df1 = df[df.Categories == 1]
len(df1)

71

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size =0.3)

## Using Gaussian Navie Bayes Classifier

In [45]:
from sklearn.naive_bayes import GaussianNB

In [46]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [47]:
gnb.predict(X_test)

array([0, 2, 2, 2, 1, 2, 0, 1, 2, 1, 1, 0, 1, 2, 2, 0, 0, 0, 1, 0, 0, 2,
       2, 2, 1, 2, 2, 1, 2, 0, 1, 0, 2, 1, 2, 0, 1, 1, 1, 0, 1, 0, 2, 2,
       1, 1, 1, 1, 1, 2, 0, 0, 1, 1])

In [50]:
X_test.head(10)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
33     13.76        1.53  2.70               19.5      132.0           2.95   
151    12.79        2.67  2.48               22.0      112.0           1.48   
174    13.40        3.91  2.48               23.0      102.0           1.80   
176    13.17        2.59  2.37               20.0      120.0           1.65   
94     11.62        1.99  2.28               18.0       98.0           3.02   
143    13.62        4.95  2.35               20.0       92.0           2.00   
2      13.16        2.36  2.67               18.6      101.0           2.80   
66     13.11        1.01  1.70               15.0       78.0           2.98   
170    12.20        3.03  2.32               19.0       96.0           1.25   
60     12.33        1.10  2.28               16.0      101.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
33         2.74                  0.50             1.35             5.40  1.25   
151        1.36                  0.24             1.26            10.80  0.48   
174        0.75                  0.43             1.41             7.30  0.70   
176        0.68                  0.53             1.46             9.30  0.60   
94         2.26                  0.17             1.35             3.25  1.16   
143        0.80                  0.47             1.02             4.40  0.91   
2          3.24                  0.30             2.81             5.68  1.03   
66         3.18                  0.26             2.28             5.30  1.12   
170        0.49                  0.40             0.73             5.50  0.66   
60         1.09                  0.63             0.41             3.27  1.25   

     od280/od315_of_diluted_wines  proline  
33                           3.00   1235.0  
151                          1.47    480.0  
174                          1.56    750.0  
176                          1.62    840.0  
94                           2.96    345.0  
143                          2.05    550.0  
2                            3.17   1185.0  
66                           3.18    502.0  
170                          1.83    510.0  
60                           1.67    680.0

In [51]:
gnb.score(X_test, y_test)

0.9814814814814815

## Using Multinomial Navie Bayes Classifier

In [53]:
from sklearn.naive_bayes import MultinomialNB

In [54]:
mnb = MultinomialNB()
mnb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [56]:
mnb.predict(X_test)

array([0, 1, 2, 2, 1, 2, 0, 1, 2, 2, 1, 0, 1, 2, 2, 0, 0, 2, 1, 0, 0, 2,
       2, 2, 1, 2, 2, 1, 1, 0, 1, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 0, 1, 2,
       1, 1, 1, 1, 1, 2, 1, 0, 2, 1])

In [58]:
mnb.score(X_test, y_test)

0.8148148148148148

## Conclusion:
Gaussian Navie Bayes is more accurate than the Multinomial Navie Byes Classifier
