In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [4]:
model.predict(np.array([4500]).reshape(1,1))

array([791660.95890411])

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [7]:
import pickle

In [8]:
with open('model_pickle','wb') as f:
    pickle.dump(model, f)

In [9]:
with open('model_pickle', 'rb') as f:
    mod = pickle.load(f)

In [10]:
mod.predict(np.array([2990]).reshape(1,1))

array([586621.57534247])

In [11]:
from sklearn.externals import joblib

C:\Users\Binod Tandan\Anaconda3\New folder\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [12]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [13]:
mj = joblib.load('model_joblib')

In [14]:
mj.predict(np.array([4700]).reshape(1,1))

array([818818.49315068])

In [15]:
mj.coef_

array([135.78767123])